# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            rockshassa
tagline:          such code. wow.
description:      such code. wow.
url:              http://rockshassa.com
baseurl:          /

author:
  name:           Nick Galasso
  url:            http://rockshassa.com
  email:          nick@rockshassa.com

paginate:         1

# Custom vars
version:          2.1.0

github:
  # repo:           https://github.com/poole/hyde
