# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               rockshassa
tagline:             such code. wow.
url:                 http://rockshassa.com
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Nick Galasso
  url:               http://rockshassa.com
  email:             nick@rockshassa.com

# Custom vars
version:             
github:
  repo:              
